# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date',
            field=models.CharField(default=b'01/01/01', max_length=25),
        ),
        migrations.AddField(
            model_name='place',
            name='notes',
            field=models.CharField(default=b'This place looks awesome!', max_length=250),
        ),
    ]
