# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20170306_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
